# Generated by Django 5.2.7 on 2025-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'offen'), ('IN_PROGRESS', 'in Bearbeitung'), ('COMPLETED', 'abgeschlossen')], default='PENDING', max_length=12)),
            ],
        ),
    ]
